# Generated by Django 5.2.8 on 2025-11-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(editable=False, primary_key=True, serialize=False),
        ),
    ]
