# Generated by Django 5.2.8 on 2025-11-25 01:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_aisteps_project_available_trusted_literatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editable_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewable_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
