# Generated by Django 5.2.8 on 2026-02-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='research_question',
            field=models.CharField(default='PLACEHOLDER RESEARCH QUESTION'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='thesis',
            field=models.CharField(blank=True),
        ),
    ]
