# Generated by Django 5.2.8 on 2026-02-08 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_project_research_question_project_thesis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='objective',
        ),
    ]
