# Generated by Django 6.0.5 on 2026-05-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_project_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='literature_sumarized',
            field=models.CharField(blank=True),
        ),
    ]
