# Generated by Django 6.0.5 on 2026-05-17 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_project_literature_sumarized'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='literature_sumarized',
            new_name='literature_summarized',
        ),
    ]
