# Generated by Django 6.0.5 on 2026-05-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_literature_sumarized_project_literature_summarized'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('basic', 'Free Tier'), ('pro', 'Professional'), ('prem', 'Premium'), ('prem_del', 'Premium Deluxe')], default='basic', max_length=10),
        ),
    ]
