# Generated by Django 6.0.5 on 2026-05-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rq_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='research_question',
            field=models.CharField(blank=True),
        ),
    ]
