# Generated by Django 6.0.5 on 2026-05-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_project_rq_mode_alter_project_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='rq_mode',
        ),
        migrations.AddField(
            model_name='project',
            name='scan_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='subtopics',
            field=models.JSONField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
