# Generated by Django 6.0.5 on 2026-05-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_project_rq_mode_project_scan_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='available_trusted_literatures',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='research_question',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.CharField(blank=True),
        ),
    ]
