# Generated by Django 6.0.6 on 2026-06-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='subtopics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
