# Generated by Django 6.0.6 on 2026-06-11 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_project_subtopics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doc',
            new_name='Manuscript',
        ),
        migrations.RemoveField(
            model_name='project',
            name='thesis',
        ),
    ]
