# Generated by Django 6.0.6 on 2026-06-11 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_doc_manuscript_remove_project_thesis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='project',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='manuscripts', to='api.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuscripts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewable_docs', to=settings.AUTH_USER_MODEL),
        ),
    ]
