# Generated by Django 6.0.6 on 2026-06-12 23:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_manuscript_project_alter_manuscript_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuscript',
            name='content',
        ),
        migrations.CreateModel(
            name='ManuscriptSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField()),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.manuscript')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
