# Generated by Django 6.0.6 on 2026-06-19 06:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_manuscript_content_manuscriptsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
