# Generated by Django 6.0.7 on 2026-07-23 12:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_manuscript_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='last_saved',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
