# Generated by Django 5.2.8 on 2025-11-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioAIPrototype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='AIsteps',
            field=models.JSONField(),
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='topic',
        ),
        migrations.AddField(
            model_name='project',
            name='objective',
            field=models.CharField(default='none'),
        ),
        migrations.DeleteModel(
            name='AIGeneratedSteps',
        ),
    ]
