# Generated by Django 5.2.8 on 2025-11-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioAIPrototype', '0002_alter_project_aisteps_rename_name_project_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
