# Generated by Django 5.2.8 on 2025-11-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioAIPrototype', '0003_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.CharField(default='a'),
            preserve_default=False,
        ),
    ]
