# Generated by Django 5.2.8 on 2025-11-24 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='AIsteps',
            new_name='available_trusted_literatures',
        ),
    ]
